config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 首頁特化的寫法
  # root "pages#index"
  root "boards#index"
  # root "boards#index"
  # get "/", to: "pages#index"
  
  get "/about", to: "pages#about"

  # resources :boards do
  #   resource :posts, only: [:index, :new, :create]
  # end

  # resource :posts, except: [:index, :new, :create]

  resources :boards do
    resources :posts, shallow: true
  end

  # member & collection
  resources :users, only: [:create] do
    collection do
      get :sign_up # 表單 --> new --> create
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

end

app/models/board.rb
class Board < ApplicationRecord

    acts_as_paranoid

    # 有設定 act_as_paranoid 的狀態下，下面這行沒有作用
    # has_many :posts, dependent: :destroy
    has_many :posts

    has_many :board_masters
    has_many :users, through: :board_masters

    # validates :title, presence: true
    validates :title, presence: true, length: { minimum: 2 }

    # 不管什麼查詢都會套用這個
    # default_scope { where(deleted_at: nil) }
    # scope :available, -> { where(deleted_at: nil) }

    # def destroy
    #   update(deleted_at: Time.now)
    # end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :find_board, only: [:show, :edit, :update, :destroy]
                            # except
  before_action :authenticate_user!, except: [:index, :show]


  layout 'application'
  # app/views/layouts/boards.html.erb
  # app/views/layouts/application.html.erb

  def index
    @boards = Board.all
    # @boards = Board.where(deleted_at: nil)
    # @boards = Board.available
  end

  def show
    # return array, 多筆資料
    # Board.where(id: params[:id]) 
    
    # return "single" value, 只會找到第一筆
    # Board.find_by(id: params[:id]) # 可以接其它欄位或 hash, 找不到 retrun nil
    # @board = Board.find(params[:id]) # 只能接 pk, 找不到 return ActiveRecord::RecordNOtFound

    # select * from boards where id = ?
  end

  def new
    # @board = Board.new
    if user_signed_in?
      @board = Board.new
    else
      redirect_to root_path, notice: '請先登入會員'
    end
  end

  def create
    @board = Board.new(board_params)
    # Board.create(title: params[:title], intro: params[:intro])

    if @board.save
      # 分段寫的話，:notice 這個 key 可以自訂
      # flash[:notice] = "新增成功"
      # redirect_to root_path

      # 只有 :notice / :alert
      redirect_to boards_path, notice: "新增成功"
    else
      # NG
      # redirect_to new_board_path, notice: "發生錯誤"
      render :new
    end

    # reander(html: params)
    # render html: params
  end

  def edit
    # @board = Board.find(params[:id])
  end

  def update
    # @board = Board.find(params[:id])

    if @board.update(board_params)
      redirect_to boards_path, notice: "更新成功"
    else
      # ng
      render :edit
    end
  end

  def destroy
    # @board = Board.find(params[:id])
    @board.destroy
    # @board.update(deleted_at: Time.now)
    redirect_to boards_path, notice: "刪除成功"
  end

  private
  def find_board
    @board = Board.find(params[:id])
  end

  # Strong Parameters
  def board_params
    params.require(:board).permit(:title, :intro)
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
  def display_bm(board)
    if board.users.count == 0
      "徵求中"
    else
      board.users.map { |user| user.account }.join("/")
    end
  end
end

app/views/boards/_form.html.erb
<% if board.errors.any?  %>
  <ul>
  <% board.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(board) do |f| %>
  <%= f.label :title, "看板名稱" %>
  <%= f.text_field :title %>

  <%= f.label :intro, "看板說明" %>
  <%= f.text_area :intro %>

  <%= f.submit "送出" %>
<% end %>

app/views/boards/edit.html.erb
<h2>編輯看板</h2>

<%= render 'form', board: @board %>

app/views/boards/index.html.erb
    <div class="row">
      <div class="title col-10 text-center my-3 mx-auto">
        <h1>看板列表</h1>
      </div>
    </div>
  
  <div class="row">
    <%= link_to "新增看板", new_board_path, class: "btn btn-info btn-sm mt-3" %>
  </div>

  <div class="row">
    <table class="table my-3 text-decoration-none">
      <thead class="thead-dark">
        <tr>
          <th>看板名稱</th>
          <th>看板狀態</th>
          <th>功能</th>
        </tr>
      </thead>
      <tbody>
        <% @boards.each do |board| %>
        <tr>
          <td>
            <%= link_to board.title, board_path(board) %>
          </td>
          <td>
            <%= board.state %>
          </td>
          <td>
            <%= link_to "編輯", edit_board_path(board) %>
            <%= link_to "刪除", board_path(board), method: 'delete', data: { confirm: '確認刪除?'} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/boards/new.html.erb
<h2>新增看板</h2>

<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<div class="row">
  <div class="title mx-auto text-center my-3">
    <h2>看板： <%= @board.title %></h2>
  </div>
</div>

<div class="row">
  <div>
  [版主：<%= display_bm(@board) %>]
  </div>
</div>

<div class="row">
  <%= link_to "新增文章", new_board_post_path(@board), class: "btn btn-info btn-sm mt-3" %>
</div>

<div class="row">
  <table class="table table-hover my-3">
    <thead class="thead">
      <tr>
        <th>文章</th>
        <th>作者</th>
        <th>功能</th>
      </tr>
    </thead>
    
    <tbody>
      <% @board.posts.each do |post| %>
      <tr>
        <td>
          <%= link_to post.title, post_path(post) %>
        </td>
        <td>
          <%= post.display_username %>
        </td>
        <td>
          <%= link_to '編輯', edit_post_path(post), class: "btn btn-primary btn-sm" %>
          <%= link_to '刪除', post_path(post), method: 'delete', data: {confirm: 'are you sure?'}, class: "btn btn-danger btn-sm" %>
        </td>
      </tr>
      <% end %>
    </tbody>

  </table>
</div>

<div class="row">
  <%= link_to "回看版列表", boards_path, class: "btn btn-sm btn-success" %>
</div>