config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 首頁特化的寫法
  # root "pages#index"
  root "boards#index"
  # root "boards#index"
  # get "/", to: "pages#index"
  
  get "/about", to: "pages#about"

  # resources :boards do
  #   resource :posts, only: [:index, :new, :create]
  # end

  # resource :posts, except: [:index, :new, :create]

  resources :boards do
    resources :posts, shallow: true
  end

  # member & collection
  resources :users, only: [:create] do
    collection do
      get :sign_up # 表單 --> new --> create
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board
  belongs_to :user

  validates :title, presence: true
  validates :serial, uniqueness: true
  # validates :serial, uniqueness: true, allow_nil: true

  # model callback life cycle: 新增跟更新
  # save -> 
  # valid -> 
  # before_validation -> 
  # validate -> 
  # after_validation -> 
  # before_save -> 
  # (before_create -> create -> after_create [update 不會走這段]) -> 
  # after_save -> 
  # after_commit

  before_create :create_serial

  # 這邊是要放在 helper 或是放在 model？
  def display_username
    user.nil? ? "未知" : user.account
  end

  private
  # self.serial 指的是 post model 中的 serial 欄位
  def create_serial
    self.serial = serial_generator(10)
    # 原型 self.serial=(serial_generator(10))
  end

  def serial_generator(n)
    [*'a'..'z', *'A'..'Z', *0..9].sample(n).join
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_board, only: [:new, :create]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]


  def new
    @post = @board.posts.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
      @post = @board.posts.new(post_params)  # 少了 user_id
      # @post.user = current_user

      if @post.save
        redirect_to @board, notice: '文章新增成功'
      else
        render :new
      end
  end

  def edit
    # @post = Post.find_by(id: params[:id], user: current_user)
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: '文章更新成功'
      # redirect_to board_path(@post.board_id) , notice: 'updated!!'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to board_path(@post.board_id)
  end

  private
  def find_board
    @board = Board.find(params[:board_id])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  # strong parameters
  def post_params
    params.require(:post)
          .permit(:title, :content)
          .merge(user: current_user) 
          # hash
          # 有 belongs_to 就可以用 :user
          # 不用！方法是因為這邊只要回傳值 而不是 改變原本的的資料
  end
end

app/views/posts/edit.html.erb
<h2><%= @post.title %></h2>

<%= form_for(@post) do |post| %>
  <div class="field">
    <%= post.label :title, "title" %>
    <%= post.text_field :title %>
  </div>

  <div class="field">
    <%= post.label :content, "content" %>
    <%= post.text_area :content %>
  </div>
  
  <%= post.submit %>
  
<% end %>

app/views/posts/new.html.erb
<h1>新增文章</h1>

<%= form_with(model: @post, url: board_posts_path, local: true) do |form| %>

  <div class="fields">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title %>
  </div>

  <div class="fields">
    <%= form.label :content, "內文" %>
    <%= form.text_area :content %>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<ul class="">
  <li>
    <div class="">
      <span>作者</span>
      <span><%= @post.user.account %></span>
    </div>
    <div class="">
      <span>看板</span>
      <span><%= @post.board.title %></span>
    </div>
  </li>

  <li>
    <span>標題:</span>
    <span><%= @post.title %></span>
  </li>
  <li>
    <span>時間:</span>
    <span><%= @post.created_at %></span>
  </li>
</ul>

<hr>

  <div class="col-12">
    <%= @post.content %>
  </div>

<%= link_to "返回", board_path(@post.board_id), class: "btn btn-sm btn-info" %>